### PR TITLE
A11y fixed issues

### PR DESCRIPTION
**Pull request by joselrio**
This PR will add several improvements for accessibility, such:
- Fixed the disabled behaviour since when a keyboard was in use to navigate though the screen it was possible to open a disabled dropdown;
- Improved the options structure in order to proper reflect the correct information about each one by changing the way focus was being managed;
- Disabled tabindex=0 at all options and set it only to the one that is focused;
- Removed live-region, once managing/update focus it will not be needed;
- aria-label was added to all the options;
- Disabled search input focus when there is no options to show;
- Added the ability to clear all the selected options when user uses the backspace or delete key;

### CODE REVIEW

**Comment by abenhamdine** [comment]
Amazing ! 🎉 
Did you run the tests ?
Because it seems there's no CI which is running tests on PR (I wish to add a workflow in a future PR if I find some time)

FI, on my windows machine, I succedeed in running the test by changing
```diff
- "test": "docsify serve docs -p 3001 & cypress run"
+ "test": "docsify serve docs -p 3001 | cypress run"
``` 

Without this change, the docsify never returns and the tests are not launched

**Comment by gnbm** [comment]
> Amazing ! 🎉 Did you run the tests ? Because it looks like there's no CI in this project which runs tests on PR (I wish I can add a workflow in a future PR if I find some time)
> 
> FI, on my windows machine, I only succedeed in running the tests by changing
> 
> ```diff
> - "test": "docsify serve docs -p 3001 & cypress run"
> + "test": "docsify serve docs -p 3001 | cypress run"
> ```
> 
> Without this change, the docsify never returns and the tests are not launched

@abenhamdine I also got that issue in the past and also, while running `npm run validate` I get some issues I'm not able to fix atm.
image

**Comment by joselrio** [comment]
> Amazing ! 🎉 Did you run the tests ? Because it looks like there's no CI in this project which runs tests on PR (I wish I can add a workflow in a future PR if I find some time)
> 
> FI, on my windows machine, I only succedeed in running the tests by changing
> 
> ```diff
> - "test": "docsify serve docs -p 3001 & cypress run"
> + "test": "docsify serve docs -p 3001 | cypress run"
> ```
> 
> Without this change, the docsify never returns and the tests are not launched

Hi [abenhamdine](https://github.com/abenhamdine).

There is 1 test failing but I do not have too much context about Cypress... 
Possible this test must be rewritten.

Cheers,
JR

**Comment by abenhamdine** [comment]
> > Amazing ! 🎉 Did you run the tests ? Because it looks like there's no CI in this project which runs tests on PR (I wish I can add a workflow in a future PR if I find some time)
> > FI, on my windows machine, I only succedeed in running the tests by changing
> > ```diff
> > - "test": "docsify serve docs -p 3001 & cypress run"
> > + "test": "docsify serve docs -p 3001 | cypress run"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Without this change, the docsify never returns and the tests are not launched
> 
> @abenhamdine I also got that issue in the past and also, while running `npm run validate` I get some issues I'm not able to fix atm. image

Yes looks like every contributor runs into these issue, doesn't look serious.

**Comment by abenhamdine** [comment]
> @abenhamdine I also got that issue in the past and also, while running npm run validate I get some issues I'm not able to fix atm.
> Basically, the solution is the same. Maybe these commands were made for someone using a Mac and are not compatible with Windows. Not sure, but I'm able to run all commands now. And in this particular case, I'm not getting any failed test

hmm  I don't think it's the same issue.
LF lint issue is due to eslint rule not appropriate for windows files
Perhaps if you use pipe operators you don't see this message anymore but it's probably due to the scss lint (the last task in the command line) hiding the output

**Review by sa-si-dev — COMMENTED** [review]
Thank you all for the contribution. I will review the code and update.

**Comment by gnbm** [comment]
> Thank you all for the contribution. I will review the code and update.

Hey @sa-si-dev 
Any ETA for a new release with these improvements reviewed?

**Comment by gnbm** [comment]
@sa-si-dev Any updated about the review of this PR?

**Review by gnbm — APPROVED** [review]
LGTM

**Pull request merged**
