### PR TITLE
Added new option searchNormalize

### PR DESCRIPTION
**Pull request by gnbm**
Added a new option called 'searchNormalize' that will allow searching by **label** ignoring diacritics in order to allow things like searching for 'Gon**c**alo' and finding 'Gon**ç**alo' or searching for 'P**o**le' and finding 'P**ô**le'.
By default, the option will be _false_.

**Note**: This can help with the issue [#238](https://github.com/sa-si-dev/virtual-select/issues/238)

### CODE REVIEW

**Comment by sa-si-dev** [comment]
@gnbm I have added you as a contributor. If you are okay with it please check all pull requests and create a new release.

**Comment by gnbm** [comment]
@sa-si-dev Sure, I can do that. Do you have any process defined or best practices for the releases? 
Will you do some of the fixes open anytime soon? Cheers and thanks

**Comment by gnbm** [comment]
@sa-si-dev  How about the documentation how do you update it and how do you prepare the release itself?

**Comment by sa-si-dev** [comment]
> @sa-si-dev  How about the documentation how do you update it and how do you prepare the release itself?
> 

@gnbm I will update the steps in the README.md

**Comment by sa-si-dev** [comment]
> > @sa-si-dev  How about the documentation how do you update it and how do you prepare the release itself?
> 
> @gnbm I will update the steps in the README.md

@gnbm I have added release steps in the README.md file

**Comment by gnbm** [comment]
@sa-si-dev I'll just wait a couple of days to see if https://github.com/sa-si-dev/virtual-select/pull/250 has more info and the changes and I'll create the release.

@sa-si-dev Do you plan to continue working on this and on some of the open issues I raised? Some I'm not comfortable enough with the code in order to try to fix them :/

**Comment by sa-si-dev** [comment]
> @sa-si-dev I'll just wait a couple of days to see if https://github.com/sa-si-dev/virtual-select/pull/250 has more info and the changes and I'll create the release.
> 
> @sa-si-dev Do you plan to continue working on this and on some of the open issues I raised? Some I'm not comfortable enough with the code in order to try to fix them :/ 

I will check and fix them when I have time.

**Pull request merged**
