### PR TITLE
Prepare v1.0.39

### PR DESCRIPTION
**Pull request by gnbm**
- Prepare v1.0.39 to make a new release

### CODE REVIEW

**Comment by gnbm** [comment]
@sa-si-dev Could you kindly take a look at the pre-release before marking it as the latest version? 
I'm having issues running cypress since the docs are served but the tests never start. Any idea?

**Comment by sa-si-dev** [comment]
> @sa-si-dev Could you kindly take a look at the pre-release before marking it as the latest version? 
> I'm having issues running cypress since the docs are served but the tests never start. Any idea?

I will check and let you know. 

Thanks for your contribution.

**Comment by sa-si-dev** [comment]
Everything looks good. You can publish the release.

FYI, I have fixed some static validation [issues](https://github.com/sa-si-dev/virtual-select/commit/78205521d4da3dc0b2c7c1a3097e4ce11d006158).

Regarding cypress, it is working fine for me and all test cases have passed successfully.
Can you give me more info about the cypress issue you have in your machine?

**Comment by gnbm** [comment]
@sa-si-dev Thanks for the feedback and for the static validation fixes.
Basically, when I run both `npm run test` and `npm run test` nothing happens after the docs get served, staying stuck in this status:
image

Probably something not well configured on my end, since I never used cypress.

**Pull request merged**
